# Generated by Django 5.2.8 on 2025-11-17 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad_maxima', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('habilitada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sala de Estudio',
                'verbose_name_plural': 'Salas de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona', models.CharField(max_length=12)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_termino', models.DateTimeField()),
                ('sala_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Sala',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
