# Generated by Django 5.2.8 on 2025-11-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='apellido_persona',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_persona',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
